apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${service_account}
  namespace: ${namespace}
  labels:
    team: ${team_name}
    app.kubernetes.io/name: team-service-account
    app.kubernetes.io/managed-by: terraform
automountServiceAccountToken: true
