apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  labels:
    app.kubernetes.io/name: coder
    app.kubernetes.io/managed-by: terraform
  annotations:
    # Keycloak OIDC Integration
    keycloak.org/namespace-group: ${keycloak_group}
    keycloak.org/namespace-realm: ${keycloak_realm}
    keycloak.org/namespace-client-id: ${keycloak_client_id}
