apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  labels:
    name: ${namespace}
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: terraform
  annotations:
    keycloak.org/namespace-group: ${namespace}
