apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${service_account_name}
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/managed-by: terraform
  annotations:
    eks.amazonaws.com/role-arn: ${iam_role_arn}
